### ISSUE TITLE
Implement The EventBridge ETL Architecture by using appropriate AWS Solutions Constructs. 

### ISSUE THREAD

**Issue by Translucent504** [panacloud-modern-global-apps/serverless-solutions-patterns-cdk#6]
# Architecture to implement:
![architecture to implement](https://user-images.githubusercontent.com/11474334/102907183-7d6d5600-4497-11eb-9cab-4c1b217c6208.png)

- [List of AWS Solutions Constructs](https://docs.aws.amazon.com/solutions/latest/constructs/api-reference.html)
- [Cdkpatterns link to read more about it](https://github.com/cdk-patterns/serverless/blob/master/the-eventbridge-etl/README.md)

**Comment by Translucent504** [comment]
Since Fargate is a  paid service, you can replace it with Lambda for now. We'll discuss how to include fargate later. :+1:  @Hamzah-syed

**Comment by Hamzah-syed** [comment]
#### Final architecture 

![Web 1920 – 1](https://user-images.githubusercontent.com/50793209/103159616-35c73100-47ed-11eb-82a9-86fed39ff8f6.png)
